#!/usr/bin/env python3
"""
Tryambakam Noesis — Product Concepts
Generated by Brandmint pipeline engine.

Provider: fal-ai
"""
import os, sys, subprocess, requests
from dotenv import load_dotenv

load_dotenv(os.path.expanduser("~/.claude/.env"))

BRAND_NAME = "Tryambakam Noesis"
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(SCRIPT_DIR, "..", "generated-v3")
os.makedirs(OUT_DIR, exist_ok=True)

# Skill reference images directory (composition references for Nano Banana Pro)
SKILL_REF_DIR = os.path.expanduser("~/.claude/skills/brandmint/references/images")

# =============================================================================
# PROVIDER CONFIGURATION
# =============================================================================
# Supports: fal (default), openrouter, openai, replicate
# Set IMAGE_PROVIDER env var or use --provider CLI flag

PROVIDER = os.environ.get("IMAGE_PROVIDER", "fal-ai").lower()

# Provider-specific imports and setup
if PROVIDER == "fal":
    try:
        import fal_client
        if not os.environ.get("FAL_KEY"):
            print("ERROR: Set FAL_KEY in ~/.claude/.env")
            sys.exit(1)
    except ImportError:
        print("ERROR: fal_client required for FAL provider. Install: pip install fal-client")
        sys.exit(1)
elif PROVIDER == "openrouter":
    if not os.environ.get("OPENROUTER_API_KEY"):
        print("ERROR: Set OPENROUTER_API_KEY in ~/.claude/.env")
        sys.exit(1)
elif PROVIDER == "openai":
    if not os.environ.get("OPENAI_API_KEY"):
        print("ERROR: Set OPENAI_API_KEY in ~/.claude/.env")
        sys.exit(1)
elif PROVIDER == "replicate":
    if not os.environ.get("REPLICATE_API_TOKEN"):
        print("ERROR: Set REPLICATE_API_TOKEN in ~/.claude/.env")
        sys.exit(1)
else:
    # Default to FAL for backward compatibility
    PROVIDER = "fal"
    try:
        import fal_client
        if not os.environ.get("FAL_KEY"):
            print("ERROR: Set FAL_KEY in ~/.claude/.env")
            sys.exit(1)
    except ImportError:
        print("ERROR: fal_client required. Install: pip install fal-client")
        sys.exit(1)

print(f"Using image provider: {PROVIDER.upper()}")

NEGATIVE = """"""

# Brand logo file (for visual reference injection — empty if no logo configured)
LOGO_PATH = ""

_logo_url_cache = None
def get_logo_url():
    """Upload brand logo once and cache the URL for reuse."""
    global _logo_url_cache
    if _logo_url_cache:
        return _logo_url_cache
    if LOGO_PATH and os.path.exists(LOGO_PATH):
        print(f"  Uploading brand logo: {os.path.basename(LOGO_PATH)}")
        if PROVIDER == "fal":
            _logo_url_cache = fal_client.upload_file(LOGO_PATH)
        else:
            # For non-FAL providers, return local path (they may not support image refs)
            _logo_url_cache = LOGO_PATH
        return _logo_url_cache
    return None


# Product reference images (actual product photos for Nano Banana Pro accuracy)
PRODUCT_REF_PATHS = []

_product_ref_url_cache = None
def get_product_ref_urls():
    """Upload product reference images once and cache URLs for reuse."""
    global _product_ref_url_cache
    if _product_ref_url_cache is not None:
        return _product_ref_url_cache
    _product_ref_url_cache = []
    for p in PRODUCT_REF_PATHS:
        if os.path.exists(p):
            print(f"  Uploading product ref: {os.path.basename(p)}")
            if PROVIDER == "fal":
                _product_ref_url_cache.append(fal_client.upload_file(p))
            else:
                _product_ref_url_cache.append(p)
    return _product_ref_url_cache


# Reference image mapping: prompt ID -> composition reference filename
REF_IMAGES = {
    "2A": "ref-2A-bento-grid.jpg",
    "2B": "ref-2B-brand-seal.jpg",
    "2C": "ref-2C-logo-emboss.jpg",
    "3A": "ref-3A-capsule-collection.jpg",
    "3B": "ref-3B-hero-product.jpg",
    "3C": "ref-3C-essence-vial.jpg",
    "4A": "ref-4A-catalog-layout.jpg",
    "4B": "ref-4B-flatlay.jpg",
    "5A": "ref-5A-heritage-engraving.jpg",
    "5B": "ref-5B-campaign-grid.jpg",
    "5D": "ref-5D-engine-icons.jpg",
    "7A": "ref-7A-contact-sheet.jpg",
    "8A": "ref-8A-seeker-poster.jpg",
    "9A": "ref-9A-engine-poster.jpg",
    "10A": "ref-7A-contact-sheet.jpg",
    "10B": "ref-7A-contact-sheet.jpg",
    "10C": "ref-7A-contact-sheet.jpg",
}

# Config-driven reference image overrides
REF_OVERRIDES = {
    "3A": "ref-alt-leather-duffles.jpg",
}
REF_IMAGES.update(REF_OVERRIDES)


def get_ref_image(pid):
    """Get composition reference image path for a prompt ID."""
    fname = REF_IMAGES.get(pid, "")
    if fname:
        path = os.path.join(SKILL_REF_DIR, fname)
        if os.path.exists(path):
            return path
    return None


def download_image(url, filepath):
    resp = requests.get(url, timeout=120)
    resp.raise_for_status()
    with open(filepath, "wb") as f:
        f.write(resp.content)
    # Auto-convert JPEG-as-PNG: Flux 2 Pro returns JPEG but pipeline names files .png
    if filepath.endswith(".png"):
        with open(filepath, "rb") as f:
            header = f.read(4)
        if header[:2] == b"\xff\xd8":  # JPEG magic bytes
            import subprocess
            subprocess.run(["sips", "-s", "format", "png", filepath, "--out", filepath],
                         capture_output=True, check=True)
            print(f"  Converted JPEG -> PNG: {os.path.getsize(filepath) // 1024} KB")
    size_kb = os.path.getsize(filepath) / 1024
    print(f"  Saved: {os.path.basename(filepath)} ({size_kb:.0f} KB)")


# =============================================================================
# PROVIDER-AWARE GENERATION FUNCTIONS
# =============================================================================

def gen_with_openrouter(prompt, model, output_path, width=1024, height=1024, **kwargs):
    """Generate image using OpenRouter API."""
    import json
    import urllib.request
    
    api_key = os.environ.get("OPENROUTER_API_KEY")
    model_map = {
        "nano-banana": "black-forest-labs/flux-1.1-pro",
        "flux-2-pro": "black-forest-labs/flux-1.1-pro",
        "recraft": "stabilityai/stable-diffusion-xl-base-1.0",
    }
    model_id = model_map.get(model, "black-forest-labs/flux-1.1-pro")
    
    payload = {"model": model_id, "prompt": prompt, "n": 1, "size": f"{width}x{height}"}
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        "https://openrouter.ai/api/v1/images/generations",
        data=data,
        headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=120) as resp:
        result = json.loads(resp.read().decode("utf-8"))
    if "data" in result and result["data"]:
        download_image(result["data"][0]["url"], output_path)
        return True
    return False


def gen_with_openai(prompt, model, output_path, width=1024, height=1024, **kwargs):
    """Generate image using OpenAI DALL-E API."""
    import json
    import urllib.request
    
    api_key = os.environ.get("OPENAI_API_KEY")
    # DALL-E 3 has fixed sizes
    if width > height:
        size = "1792x1024"
    elif height > width:
        size = "1024x1792"
    else:
        size = "1024x1024"
    
    payload = {"model": "dall-e-3", "prompt": prompt, "n": 1, "size": size, "quality": "hd"}
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        "https://api.openai.com/v1/images/generations",
        data=data,
        headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=120) as resp:
        result = json.loads(resp.read().decode("utf-8"))
    if "data" in result and result["data"]:
        download_image(result["data"][0]["url"], output_path)
        return True
    return False


def gen_with_replicate(prompt, model, output_path, width=1024, height=1024, **kwargs):
    """Generate image using Replicate API."""
    import json
    import time
    import urllib.request
    
    api_key = os.environ.get("REPLICATE_API_TOKEN")
    model_map = {
        "nano-banana": "black-forest-labs/flux-1.1-pro",
        "flux-2-pro": "black-forest-labs/flux-1.1-pro",
        "recraft": "stability-ai/sdxl:39ed52f2a78e934b3ba6e2a89f5b1c712de7dfea535525255b1aa35c5565e08b",
    }
    model_id = model_map.get(model, "black-forest-labs/flux-1.1-pro")
    
    # Create prediction
    payload = {"input": {"prompt": prompt, "width": width, "height": height}}
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        f"https://api.replicate.com/v1/models/{model_id}/predictions",
        data=data,
        headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        pred = json.loads(resp.read().decode("utf-8"))
    
    # Poll for completion
    pred_id = pred.get("id")
    for _ in range(60):
        time.sleep(5)
        req = urllib.request.Request(
            f"https://api.replicate.com/v1/predictions/{pred_id}",
            headers={"Authorization": f"Bearer {api_key}"},
        )
        with urllib.request.urlopen(req, timeout=30) as resp:
            result = json.loads(resp.read().decode("utf-8"))
        if result.get("status") == "succeeded":
            output = result.get("output")
            url = output[0] if isinstance(output, list) else output
            download_image(url, output_path)
            return True
        if result.get("status") in ("failed", "canceled"):
            return False
    return False


def gen_nano_banana(pid, slug, prompt, aspect, image_urls, seeds=(42, 137)):
    """Generate with Nano Banana Pro + style anchor (or equivalent on other providers)."""
    full_prompt = f"{prompt}\n\nAvoid: {NEGATIVE}"

    # Parse aspect ratio to get dimensions
    aspect_dims = {"16:9": (1792, 1024), "9:16": (1024, 1792), "1:1": (1024, 1024),
                   "3:4": (896, 1152), "4:3": (1152, 896)}
    w, h = aspect_dims.get(aspect, (1024, 1024))

    for seed in seeds:
        variant = "v1" if seed == 42 else f"v{seed}"
        out_path = os.path.join(OUT_DIR, f"{pid}-{slug}-nanobananapro-{variant}.png")
        print(f"\n  [{pid}] Nano Banana Pro seed={seed} (provider: {PROVIDER})...")

        if PROVIDER == "fal":
            result = fal_client.subscribe(
                "fal-ai/nano-banana-pro",
                arguments={
                    "prompt": full_prompt,
                    "image_urls": image_urls,
                    "aspect_ratio": aspect,
                    "resolution": "2K",
                    "output_format": "png",
                    "seed": seed,
                    "num_images": 1,
                },
            )
            download_image(result["images"][0]["url"], out_path)
        elif PROVIDER == "openrouter":
            gen_with_openrouter(full_prompt, "nano-banana", out_path, w, h)
        elif PROVIDER == "openai":
            gen_with_openai(full_prompt, "nano-banana", out_path, w, h)
        elif PROVIDER == "replicate":
            gen_with_replicate(full_prompt, "nano-banana", out_path, w, h)


def gen_flux_pro(pid, slug, prompt, aspect, seeds=(42, 137)):
    """Generate with Flux 2 Pro (or equivalent on other providers)."""
    full_prompt = f"{prompt}\n\nAvoid: {NEGATIVE}"

    # Parse aspect to dimensions
    aspect_dims = {"landscape_16_9": (1792, 1024), "portrait_9_16": (1024, 1792),
                   "square": (1024, 1024), "portrait_3_4": (896, 1152), "landscape_4_3": (1152, 896)}
    w, h = aspect_dims.get(aspect, (1024, 1024))

    for seed in seeds:
        variant = "v1" if seed == 42 else f"v{seed}"
        out_path = os.path.join(OUT_DIR, f"{pid}-{slug}-flux2pro-{variant}.png")
        print(f"\n  [{pid}] Flux 2 Pro seed={seed} (provider: {PROVIDER})...")

        if PROVIDER == "fal":
            result = fal_client.subscribe(
                "fal-ai/flux-2-pro",
                arguments={
                    "prompt": full_prompt,
                    "image_size": aspect,
                    "num_images": 1,
                    "seed": seed,
                },
            )
            download_image(result["images"][0]["url"], out_path)
        elif PROVIDER == "openrouter":
            gen_with_openrouter(full_prompt, "flux-2-pro", out_path, w, h)
        elif PROVIDER == "openai":
            gen_with_openai(full_prompt, "flux-2-pro", out_path, w, h)
        elif PROVIDER == "replicate":
            gen_with_replicate(full_prompt, "flux-2-pro", out_path, w, h)


PROMPT_3A = """Tryambakam Noesis capsule collection product lineup.
Three products in a row on polished surface: bio-digital notebook with custom spine,
small glass vessel, and symbolic craft object.
Materials: . Environment: .
. . Camera: . 8K detail.
Color palette: Witness Violet 60% backgrounds. Flow Indigo 30% text/surfaces. Sacred Gold 10% highlights ONLY. #2D0050 deep shadows, #0B50FB highlights,
#C5A017 reflections, #10B5A7 living accents.
Audience aesthetic: . Must feel like it belongs in the world of ."""

PROMPT_3B = """Tryambakam Noesis hero product shot. hardcover codex with custom spine in Sacred Gold (#C5A017) material, pages made of fine craft paper, geometric diagrams visible on open pages in SF Mono.
Sitting on polished surface. . Environment: .
. Camera: . Materials: . 8K."""

PROMPT_3C = """Tryambakam Noesis essence product shot. Small borosilicate glass bottle with oxidized metal dropper cap
(30ml). Etched label directly into surface in SF Mono.
Brand name "Tryambakam Noesis" etched dominant. Minimal sigil below. Pure solid
Witness Violet (#2D0050) background. Sharp high-contrast lighting from above.
Sacred Gold highlight, Flow Indigo edge-glow.
. 8K."""

PROMPT_4A = """Tryambakam Noesis product design catalog page. Top section: lifestyle product image of five engine-matched essential oil attar vials (15ml amber glass, brushed bronze dropper caps) arranged in a precise arc on matte Void Black (#070B1D) surface. Each vial has a different engine name etched in SF Mono and filled with Sacred Gold (#C5A017) pigment. Dark-field lighting -- single directional warm light from upper-left. Sacred Gold highlights on bronze caps. Coherence Emerald (#10B5A7) edge-glow on glass silhouettes. Deep shadows. No external context.

Bottom section: technical specification panel -- architectural line drawings in Sacred Gold (#C5A017) on Void Black (#070B1D) background. Front elevation of vial with cap, side cross-section showing dropper mechanism, top-down view of cap geometry. Fine hairline technical lines with measurement callouts in SF Mono. Material swatches panel: amber glass, brushed bronze, Sacred Gold pigment fill. 1px Muted Silver (#8A9BA8) borders. Overall: precision product catalog. Bioluminescent. Architectural."""

PROMPT_4B = """High-contrast dark-field product photograph of the Tryambakam Noesis ritual object collection. Overhead knolling composition on matte Void Black (#070B1D) surface. Five objects arranged in precise sacred geometry spacing (golden ratio proportions between objects):

1. Bronze orgonite pyramid with Coherence Emerald (#10B5A7) resin core
2. Amber glass attar vial with bronze cap, Sacred Gold (#C5A017) etched sigil
3. Unglazed dark ceramic incense holder with impressed resonance pattern
4. Bronze compass pendant on black cord -- four direction markers visible
5. Matte black practice journal with blind-embossed sigil

Overhead flat-lay. Each object casting a single sharp shadow. A faint Sacred Gold constellation grid drawn between objects on the surface -- like a field map connecting them geometrically.

Single directional warm light from upper-left. Sacred Gold highlights on bronze surfaces. Coherence Emerald bio-glow from orgonite core. Void Black surface reflects nothing. Camera: overhead 80mm equivalent, f/8, 8K detail on bronze patina, ceramic grain, glass refraction. Color palette: #070B1D 70% background, #C5A017 20% bronze highlights, #10B5A7 10% emerald glow. No external environment. The objects emerge from darkness."""


def main():
    print("=" * 60)
    print(f"{BRAND_NAME} -- Product Concepts")
    print("Model: Flux 2 Pro / Nano Banana Pro")
    print("=" * 60)

    print("\n--- 3A: Capsule Collection ---")
    gen_flux_pro("3A", "capsule-collection", PROMPT_3A, "landscape_16_9")

    print("\n--- 3B: Hero Book / Codex ---")
    gen_flux_pro("3B", "hero-book", PROMPT_3B, "portrait_4_3")

    print("\n--- 3C: Essence Vial ---")
    gen_flux_pro("3C", "essence-vial", PROMPT_3C, "square_hd")

    print("\n--- 4A: Catalog Layout ---")
    # Nano Banana Pro needs style anchor images
    image_urls = []
    ref_4a = get_ref_image("4A")
    if ref_4a:
        print(f"  Adding composition ref: {os.path.basename(ref_4a)}")
        if PROVIDER == "fal":
            image_urls.append(fal_client.upload_file(ref_4a))
        else:
            image_urls.append(ref_4a)
    gen_nano_banana("4A", "catalog-layout", PROMPT_4A, "4:3", image_urls)

    print("\n--- 4B: Flatlay ---")
    gen_flux_pro("4B", "flatlay", PROMPT_4B, "square_hd")

    print("\n" + "=" * 60)
    print("  PRODUCTS COMPLETE")
    print("=" * 60)


if __name__ == "__main__":
    main()
