#!/usr/bin/env python3
"""
Tryambakam Noesis — Illustrations + Icons (5A-5D)
Generated by Brandmint pipeline engine.

Provider: fal-ai
"""
import os, sys, subprocess, requests
from dotenv import load_dotenv

load_dotenv(os.path.expanduser("~/.claude/.env"))

BRAND_NAME = "Tryambakam Noesis"
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(SCRIPT_DIR, "..", "generated-v3")
os.makedirs(OUT_DIR, exist_ok=True)

# Skill reference images directory (composition references for Nano Banana Pro)
SKILL_REF_DIR = os.path.expanduser("~/.claude/skills/brandmint/references/images")

# =============================================================================
# PROVIDER CONFIGURATION
# =============================================================================
# Supports: fal (default), openrouter, openai, replicate
# Set IMAGE_PROVIDER env var or use --provider CLI flag

PROVIDER = os.environ.get("IMAGE_PROVIDER", "fal-ai").lower()

# Provider-specific imports and setup
if PROVIDER == "fal":
    try:
        import fal_client
        if not os.environ.get("FAL_KEY"):
            print("ERROR: Set FAL_KEY in ~/.claude/.env")
            sys.exit(1)
    except ImportError:
        print("ERROR: fal_client required for FAL provider. Install: pip install fal-client")
        sys.exit(1)
elif PROVIDER == "openrouter":
    if not os.environ.get("OPENROUTER_API_KEY"):
        print("ERROR: Set OPENROUTER_API_KEY in ~/.claude/.env")
        sys.exit(1)
elif PROVIDER == "openai":
    if not os.environ.get("OPENAI_API_KEY"):
        print("ERROR: Set OPENAI_API_KEY in ~/.claude/.env")
        sys.exit(1)
elif PROVIDER == "replicate":
    if not os.environ.get("REPLICATE_API_TOKEN"):
        print("ERROR: Set REPLICATE_API_TOKEN in ~/.claude/.env")
        sys.exit(1)
else:
    # Default to FAL for backward compatibility
    PROVIDER = "fal"
    try:
        import fal_client
        if not os.environ.get("FAL_KEY"):
            print("ERROR: Set FAL_KEY in ~/.claude/.env")
            sys.exit(1)
    except ImportError:
        print("ERROR: fal_client required. Install: pip install fal-client")
        sys.exit(1)

print(f"Using image provider: {PROVIDER.upper()}")

NEGATIVE = """"""

# Brand logo file (for visual reference injection — empty if no logo configured)
LOGO_PATH = ""

_logo_url_cache = None
def get_logo_url():
    """Upload brand logo once and cache the URL for reuse."""
    global _logo_url_cache
    if _logo_url_cache:
        return _logo_url_cache
    if LOGO_PATH and os.path.exists(LOGO_PATH):
        print(f"  Uploading brand logo: {os.path.basename(LOGO_PATH)}")
        if PROVIDER == "fal":
            _logo_url_cache = fal_client.upload_file(LOGO_PATH)
        else:
            # For non-FAL providers, return local path (they may not support image refs)
            _logo_url_cache = LOGO_PATH
        return _logo_url_cache
    return None


# Product reference images (actual product photos for Nano Banana Pro accuracy)
PRODUCT_REF_PATHS = []

_product_ref_url_cache = None
def get_product_ref_urls():
    """Upload product reference images once and cache URLs for reuse."""
    global _product_ref_url_cache
    if _product_ref_url_cache is not None:
        return _product_ref_url_cache
    _product_ref_url_cache = []
    for p in PRODUCT_REF_PATHS:
        if os.path.exists(p):
            print(f"  Uploading product ref: {os.path.basename(p)}")
            if PROVIDER == "fal":
                _product_ref_url_cache.append(fal_client.upload_file(p))
            else:
                _product_ref_url_cache.append(p)
    return _product_ref_url_cache


# Reference image mapping: prompt ID -> composition reference filename
REF_IMAGES = {
    "2A": "ref-2A-bento-grid.jpg",
    "2B": "ref-2B-brand-seal.jpg",
    "2C": "ref-2C-logo-emboss.jpg",
    "3A": "ref-3A-capsule-collection.jpg",
    "3B": "ref-3B-hero-product.jpg",
    "3C": "ref-3C-essence-vial.jpg",
    "4A": "ref-4A-catalog-layout.jpg",
    "4B": "ref-4B-flatlay.jpg",
    "5A": "ref-5A-heritage-engraving.jpg",
    "5B": "ref-5B-campaign-grid.jpg",
    "5D": "ref-5D-engine-icons.jpg",
    "7A": "ref-7A-contact-sheet.jpg",
    "8A": "ref-8A-seeker-poster.jpg",
    "9A": "ref-9A-engine-poster.jpg",
    "10A": "ref-7A-contact-sheet.jpg",
    "10B": "ref-7A-contact-sheet.jpg",
    "10C": "ref-7A-contact-sheet.jpg",
}

# Config-driven reference image overrides
REF_OVERRIDES = {
    "3A": "ref-alt-leather-duffles.jpg",
}
REF_IMAGES.update(REF_OVERRIDES)


def get_ref_image(pid):
    """Get composition reference image path for a prompt ID."""
    fname = REF_IMAGES.get(pid, "")
    if fname:
        path = os.path.join(SKILL_REF_DIR, fname)
        if os.path.exists(path):
            return path
    return None


def download_image(url, filepath):
    resp = requests.get(url, timeout=120)
    resp.raise_for_status()
    with open(filepath, "wb") as f:
        f.write(resp.content)
    # Auto-convert JPEG-as-PNG: Flux 2 Pro returns JPEG but pipeline names files .png
    if filepath.endswith(".png"):
        with open(filepath, "rb") as f:
            header = f.read(4)
        if header[:2] == b"\xff\xd8":  # JPEG magic bytes
            import subprocess
            subprocess.run(["sips", "-s", "format", "png", filepath, "--out", filepath],
                         capture_output=True, check=True)
            print(f"  Converted JPEG -> PNG: {os.path.getsize(filepath) // 1024} KB")
    size_kb = os.path.getsize(filepath) / 1024
    print(f"  Saved: {os.path.basename(filepath)} ({size_kb:.0f} KB)")


# =============================================================================
# PROVIDER-AWARE GENERATION FUNCTIONS
# =============================================================================

def gen_with_openrouter(prompt, model, output_path, width=1024, height=1024, **kwargs):
    """Generate image using OpenRouter API."""
    import json
    import urllib.request
    
    api_key = os.environ.get("OPENROUTER_API_KEY")
    model_map = {
        "nano-banana": "black-forest-labs/flux-1.1-pro",
        "flux-2-pro": "black-forest-labs/flux-1.1-pro",
        "recraft": "stabilityai/stable-diffusion-xl-base-1.0",
    }
    model_id = model_map.get(model, "black-forest-labs/flux-1.1-pro")
    
    payload = {"model": model_id, "prompt": prompt, "n": 1, "size": f"{width}x{height}"}
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        "https://openrouter.ai/api/v1/images/generations",
        data=data,
        headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=120) as resp:
        result = json.loads(resp.read().decode("utf-8"))
    if "data" in result and result["data"]:
        download_image(result["data"][0]["url"], output_path)
        return True
    return False


def gen_with_openai(prompt, model, output_path, width=1024, height=1024, **kwargs):
    """Generate image using OpenAI DALL-E API."""
    import json
    import urllib.request
    
    api_key = os.environ.get("OPENAI_API_KEY")
    # DALL-E 3 has fixed sizes
    if width > height:
        size = "1792x1024"
    elif height > width:
        size = "1024x1792"
    else:
        size = "1024x1024"
    
    payload = {"model": "dall-e-3", "prompt": prompt, "n": 1, "size": size, "quality": "hd"}
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        "https://api.openai.com/v1/images/generations",
        data=data,
        headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=120) as resp:
        result = json.loads(resp.read().decode("utf-8"))
    if "data" in result and result["data"]:
        download_image(result["data"][0]["url"], output_path)
        return True
    return False


def gen_with_replicate(prompt, model, output_path, width=1024, height=1024, **kwargs):
    """Generate image using Replicate API."""
    import json
    import time
    import urllib.request
    
    api_key = os.environ.get("REPLICATE_API_TOKEN")
    model_map = {
        "nano-banana": "black-forest-labs/flux-1.1-pro",
        "flux-2-pro": "black-forest-labs/flux-1.1-pro",
        "recraft": "stability-ai/sdxl:39ed52f2a78e934b3ba6e2a89f5b1c712de7dfea535525255b1aa35c5565e08b",
    }
    model_id = model_map.get(model, "black-forest-labs/flux-1.1-pro")
    
    # Create prediction
    payload = {"input": {"prompt": prompt, "width": width, "height": height}}
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        f"https://api.replicate.com/v1/models/{model_id}/predictions",
        data=data,
        headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        pred = json.loads(resp.read().decode("utf-8"))
    
    # Poll for completion
    pred_id = pred.get("id")
    for _ in range(60):
        time.sleep(5)
        req = urllib.request.Request(
            f"https://api.replicate.com/v1/predictions/{pred_id}",
            headers={"Authorization": f"Bearer {api_key}"},
        )
        with urllib.request.urlopen(req, timeout=30) as resp:
            result = json.loads(resp.read().decode("utf-8"))
        if result.get("status") == "succeeded":
            output = result.get("output")
            url = output[0] if isinstance(output, list) else output
            download_image(url, output_path)
            return True
        if result.get("status") in ("failed", "canceled"):
            return False
    return False


def gen_recraft(pid, slug, prompt, style, colors, size, seeds=(42, 137)):
    """Generate with Recraft V3 (or SDXL equivalent on other providers)."""
    # Parse size to dimensions for non-FAL providers
    size_dims = {"square": (1024, 1024), "landscape_16_9": (1792, 1024), 
                 "portrait_9_16": (1024, 1792), "1024x1024": (1024, 1024)}
    w, h = size_dims.get(size, (1024, 1024))
    
    for seed in seeds:
        variant = "v1" if seed == 42 else f"v{seed}"
        base_name = f"{pid}-{slug}-recraft-{variant}"
        print(f"\n  [{pid}] Recraft V3 ({style}) seed={seed} (provider: {PROVIDER})...")
        
        if PROVIDER == "fal":
            print(f"  Prompt length: {len(prompt)} chars")
            args = {
                "prompt": prompt,
                "image_size": size,
                "style": style,
                "seed": seed,
            }
            if colors:
                args["colors"] = [{"rgb": c} for c in colors]
            result = fal_client.subscribe(
                "fal-ai/recraft/v3/text-to-image",
                arguments=args,
            )
            img_url = result["images"][0]["url"]
            is_svg = img_url.endswith(".svg") or "vector" in style
            if is_svg:
                native_path = os.path.join(OUT_DIR, f"{base_name}.svg")
                download_image(img_url, native_path)
                png_path = os.path.join(OUT_DIR, f"{base_name}.png")
                try:
                    subprocess.run(
                        ["rsvg-convert", "-w", "2048", "-h", "2048",
                         "--keep-aspect-ratio", native_path, "-o", png_path],
                        check=True, capture_output=True,
                    )
                    sz = os.path.getsize(png_path) / 1024
                    print(f"  Converted SVG -> PNG: {sz:.0f} KB")
                except (subprocess.CalledProcessError, FileNotFoundError) as e:
                    print(f"  WARNING: SVG->PNG failed: {e}")
            else:
                native_path = os.path.join(OUT_DIR, f"{base_name}.webp")
                download_image(img_url, native_path)
                png_path = os.path.join(OUT_DIR, f"{base_name}.png")
                try:
                    subprocess.run(
                        ["sips", "-s", "format", "png", native_path, "--out", png_path],
                        check=True, capture_output=True,
                    )
                    sz = os.path.getsize(png_path) / 1024
                    print(f"  Converted WebP -> PNG: {sz:.0f} KB")
                except (subprocess.CalledProcessError, FileNotFoundError) as e:
                    print(f"  WARNING: WebP->PNG failed: {e}")
        else:
            # Non-FAL providers: use SDXL or equivalent (no SVG support)
            out_path = os.path.join(OUT_DIR, f"{base_name}.png")
            enhanced_prompt = f"{prompt}. Style: {style}. Fine line art, detailed illustration."
            if PROVIDER == "openrouter":
                gen_with_openrouter(enhanced_prompt, "recraft", out_path, w, h)
            elif PROVIDER == "openai":
                gen_with_openai(enhanced_prompt, "recraft", out_path, w, h)
            elif PROVIDER == "replicate":
                gen_with_replicate(enhanced_prompt, "recraft", out_path, w, h)


def gen_nano_banana(pid, slug, prompt, aspect, image_urls, seeds=(42, 137)):
    """Generate with Nano Banana Pro + style anchor (or equivalent on other providers)."""
    full_prompt = f"{prompt}\n\nAvoid: {NEGATIVE}"
    
    # Parse aspect ratio to get dimensions
    aspect_dims = {"16:9": (1792, 1024), "9:16": (1024, 1792), "1:1": (1024, 1024), 
                   "3:4": (896, 1152), "4:3": (1152, 896)}
    w, h = aspect_dims.get(aspect, (1024, 1024))
    
    for seed in seeds:
        variant = "v1" if seed == 42 else f"v{seed}"
        out_path = os.path.join(OUT_DIR, f"{pid}-{slug}-nanobananapro-{variant}.png")
        print(f"\n  [{pid}] Nano Banana Pro seed={seed} (provider: {PROVIDER})...")
        
        if PROVIDER == "fal":
            result = fal_client.subscribe(
                "fal-ai/nano-banana-pro",
                arguments={
                    "prompt": full_prompt,
                    "image_urls": image_urls,
                    "aspect_ratio": aspect,
                    "resolution": "2K",
                    "output_format": "png",
                    "seed": seed,
                    "num_images": 1,
                },
            )
            download_image(result["images"][0]["url"], out_path)
        elif PROVIDER == "openrouter":
            gen_with_openrouter(full_prompt, "nano-banana", out_path, w, h)
        elif PROVIDER == "openai":
            gen_with_openai(full_prompt, "nano-banana", out_path, w, h)
        elif PROVIDER == "replicate":
            gen_with_replicate(full_prompt, "nano-banana", out_path, w, h)


def gen_flux_pro(pid, slug, prompt, aspect, seeds=(42, 137)):
    """Generate with Flux 2 Pro (or equivalent on other providers)."""
    full_prompt = f"{prompt}\n\nAvoid: {NEGATIVE}"
    
    # Parse aspect to dimensions
    aspect_dims = {"landscape_16_9": (1792, 1024), "portrait_9_16": (1024, 1792), 
                   "square": (1024, 1024), "portrait_3_4": (896, 1152), "landscape_4_3": (1152, 896)}
    w, h = aspect_dims.get(aspect, (1024, 1024))
    
    for seed in seeds:
        variant = "v1" if seed == 42 else f"v{seed}"
        out_path = os.path.join(OUT_DIR, f"{pid}-{slug}-flux2pro-{variant}.png")
        print(f"\n  [{pid}] Flux 2 Pro seed={seed} (provider: {PROVIDER})...")
        
        if PROVIDER == "fal":
            result = fal_client.subscribe(
                "fal-ai/flux-2-pro",
                arguments={
                    "prompt": full_prompt,
                    "image_size": aspect,
                    "num_images": 1,
                    "seed": seed,
                },
            )
            download_image(result["images"][0]["url"], out_path)
        elif PROVIDER == "openrouter":
            gen_with_openrouter(full_prompt, "flux-2-pro", out_path, w, h)
        elif PROVIDER == "openai":
            gen_with_openai(full_prompt, "flux-2-pro", out_path, w, h)
        elif PROVIDER == "replicate":
            gen_with_replicate(full_prompt, "flux-2-pro", out_path, w, h)


PROMPT_5A = """Tryambakam Noesis heritage engraving logomark. .
Thin delicate hairlines in organic curves. Airy, precise, no heavy borders.
Central sigil: . . Rendered as
botanical-scientific diagram. "Tryambakam Noesis" in geometric serif (Panchang
style), wide spacing. Below: "EST. MMXXVI" lighter weight. Flow Indigo
(#0B50FB) paper. Witness Violet (#2D0050) lines. Sacred Gold
(#C5A017) accent on borders."""

PROMPT_5B = """Tryambakam Noesis Campaign Visual Identity Grid. 2-column
asymmetrical layout. Full bleed, zero spacing between tiles.
Core metaphor: . Visual territory: .
TYPE A: Solid Witness Violet (#2D0050) background with pattern at 5% opacity,
centered sigil in Flow Indigo (#0B50FB).
TYPE B: Sacred Gold (#C5A017) background, "Self-Consciousness as Technology. Body as Medium. Breath as Interface." in Panchang
SemiBold, Flow Indigo text.
TYPE C: High-contrast duotone photographs using #2D0050 + #C5A017.
Materials: . . Typography: Panchang ONLY.
Witness Violet 60% backgrounds. Flow Indigo 30% text/surfaces. Sacred Gold 10% highlights ONLY. Every photo unique. ."""

PROMPT_5C = """Tryambakam Noesis conceptual panel illustration. .
. Core metaphor: . Mood: .
Flowing organic lines, flat color planes in Witness Violet
(#2D0050), Sacred Gold (#C5A017), and Coherence Emerald (#10B5A7).
Witness Violet 60% backgrounds. Flow Indigo 30% text/surfaces. Sacred Gold 10% highlights ONLY. Decorative border of flowing curves and organic tendrils. Grounded figure on
polished surface. Bio-digital structure elements with fiber-optic filaments
glowing Flow Indigo. No mystical imagery. Paper texture: warm, fibrous."""

PROMPT_7A = """Tryambakam Noesis -- "The Anatomist Who Sees Fractals" editorial contact sheet. 3x3 grid of 9 panels showing hands-only dark-field photography. No face visible -- only hands and forearms in dark structured clothing. Same hands across all 9 panels.

9 PANELS:
1. Overhead: hands on open Somatic Canticles volume, Sacred Gold compass diagram visible on Parchment pages
2. Right hand holding fine-point pen hovering over half-finished sacred geometry diagram in Sacred Gold ink on black paper
3. Both hands arranging five amber glass attar vials in precise arc on Void Black surface
4. Right hand mid-page-turn, Parchment paper edge catching Sacred Gold directional light
5. Both hands holding bronze resonance pendant at chest level from behind, compass geometry catching light
6. Index finger tracing the resonance pattern sigil etched into a bronze disc, Sacred Gold patina following the trace
7. Hands breaking open a dark wax seal on black paper, Sacred Gold fragments visible
8. Forearms resting on dark surface, 16 small engine diagram cards printed in Sacred Gold on black, spread in 4x4 grid
9. Right hand lighting incense in unglazed ceramic holder with impressed sigil, first smoke wisps catching warm light

Camera: 80mm equivalent, f/8. Dark-field lighting throughout -- single directional warm from upper-left. No visible light source. Subject emerges from Void Black (#070B1D). Sacred Gold (#C5A017) highlights on bronze and glass. Coherence Emerald (#10B5A7) glow where orgonite or resin objects appear. 2px Muted Silver (#8A9BA8) borders between panels. 8K detail on hand texture, material grain, bronze patina."""

PROMPT_3C = """Manga episode cover: The Plumber -- solitary figure from behind at base of vast vertebral column rising through concentric sacred geometry into Void Black (#070B1D). Minimalist black-and-white manga style -- clean linework, flat Parchment (#F0EDE3), sharp shadows. Structured minimal clothing. Anatomical spine -- each vertebra distinct, Sacred Gold (#C5A017) wireframe geometry radiating from spine. Complexity increases upward -- compass points at lumbar, mandala at cervical, resonance sigil at crown. No mystical imagery, no lotus, no third eye. Architecture of body IS sacred geometry. Void Black background, faint constellation grid. Title: "THE PLUMBER — EPISODE I" Panchang font, Sacred Gold."""

PROMPT_3D1 = """4 minimalist sacred geometry icons for Tryambakam Noesis "Vedic Engines" in 2x2 grid layout.

LINE WORK: Precision geometric linework -- clean, structural, load-bearing geometry (not decorative). Uniform weight monoline outlines.
STYLE: Only Void Black (#070B1D) and Parchment (#F0EDE3). No shading, no gradients.

THE 4 ICONS:
1. Temporal Grammar (Panchanga) -- Five concentric rings with different geometric subdivisions representing the five limbs of Vedic time
2. Chronofield -- Orbital rings with planetary position markers, 120-year cycle segments visible
3. Bioelectric Field -- Concentric body silhouette radiating field lines with compass geometry overlay
4. Energetic Authority -- Bodygraph diamond form with connecting channels and authority-type markers

Clean 2x2 grid on Parchment background. Each icon in square frame with 1px Void Black border. SF Mono label below each icon."""

PROMPT_3D2 = """4 minimalist sacred geometry icons for Tryambakam Noesis "Western Engines" in 2x2 grid layout.

LINE WORK: Precision geometric linework. Uniform weight monoline outlines.
STYLE: Only Void Black (#070B1D) and Parchment (#F0EDE3). No shading, no gradients.

THE 4 ICONS:
5. Gift-Shadow Spectrum -- Three-tiered wave (shadow/gift/siddhi) with developmental arc arrow
6. Active Planetary Weather -- Globe with meridian lines, transit arrows, current-position marker
7. Nine-Point Architecture -- 9-pointed geometric figure with interconnecting lines and fixation markers
8. Numeric Architecture -- Digits 0-9 arranged in Fibonacci spiral formation

Clean 2x2 grid on Parchment background. Square frames. 1px borders. SF Mono labels."""

PROMPT_3D3 = """3 minimalist sacred geometry icons for Tryambakam Noesis "Bridge Engines" in 2-top 1-bottom layout.

LINE WORK: Precision geometric. Uniform monoline outlines.
STYLE: Only Void Black (#070B1D) and Parchment (#F0EDE3). No shading, no gradients.

THE 3 ICONS:
9. Archetypal Mirror -- Single card silhouette with geometric interior pattern (78-card reference)
10. Circadian Cartography -- 12-segment circular clock face with organ-system annotations at each segment
11. Three-Wave Cycle -- Three overlapping sine waves (Physical, Emotional, Intellectual) with phase markers

Clean grid on Parchment background. Square frames. SF Mono labels."""

PROMPT_3D4 = """3 minimalist sacred geometry icons for Tryambakam Noesis "Somatic & Resonance Engines" in 2-top 1-bottom layout.

LINE WORK: Precision geometric. Uniform monoline outlines.
STYLE: Only Void Black (#070B1D) and Parchment (#F0EDE3). No shading, no gradients.

THE 3 ICONS:
12. Physiognomic Mapping -- Face silhouette with proportional measurement grid overlay
13. Resonance Architecture -- Acoustic frequency waveform with ascending harmonic series visualization
14. Hexagram Navigation -- Six-line hexagram stack (I Ching-inspired) with 64-state grid reference

Clean grid on Parchment background. Square frames. SF Mono labels."""

PROMPT_3D5 = """2 minimalist sacred geometry icons for Tryambakam Noesis "Forge & Geometry Engines" side-by-side.

LINE WORK: Precision geometric. Uniform monoline outlines.
STYLE: Only Void Black (#070B1D) and Parchment (#F0EDE3). No shading, no gradients.

THE 2 ICONS:
15. Geometric Resonance -- Nested platonic solids (tetrahedron inside icosahedron inside sphere) with proportional reference lines
16. Sigil Forge -- Geometric glyph construction diagram with compass and protractor reference marks

Clean side-by-side on Parchment background. Square frames. SF Mono labels."""

STYLE_ANCHOR = os.path.join(OUT_DIR, "2A-brand-kit-bento-nanobananapro-v1.png")


def main():
    print("=" * 60)
    print(f"{BRAND_NAME} -- Illustrations + Icons (5A-5D)")
    print("=" * 60)

    # Verify Recraft prompt lengths
    recraft_prompts = {
        "5A": PROMPT_5A,
        "5C": PROMPT_5C,
        "3C": PROMPT_3C,
        "3D1": PROMPT_3D1,
        "3D2": PROMPT_3D2,
        "3D3": PROMPT_3D3,
        "3D4": PROMPT_3D4,
        "3D5": PROMPT_3D5
    }
    for pid, p in recraft_prompts.items():
        count = len(p)
        status = "OK" if count < 1000 else "OVER LIMIT"
        print(f"  {pid}: {count} chars [{status}]")
        if count >= 1000:
            print("ERROR: Prompt exceeds 1000 char Recraft V3 limit. Condense it.")
            sys.exit(1)

    # 5A: Heritage Engraving (Recraft digital_illustration)
    print("\n--- 5A: Heritage Engraving (Recraft V3 digital) ---")
    gen_recraft("5A", "heritage-engraving", PROMPT_5A,
                "digital_illustration",
                ["#2D0050", "#0B50FB", "#C5A017"],
                "square_hd")

    # 5B: Campaign Grid (Nano Banana Pro + anchor + comp ref)
    print("\n--- 5B: Campaign Grid (Nano Banana Pro) ---")
    anchor_urls = []
    if os.path.exists(STYLE_ANCHOR):
        anchor_url = fal_client.upload_file(STYLE_ANCHOR)
        anchor_urls = [anchor_url]
    logo_url = get_logo_url()
    if logo_url:
        anchor_urls.append(logo_url)
    ref_5b = get_ref_image("5B")
    if ref_5b:
        print(f"  Adding composition ref: {os.path.basename(ref_5b)}")
        anchor_urls.append(fal_client.upload_file(ref_5b))
    gen_nano_banana("5B", "campaign-grid", PROMPT_5B, "3:4", anchor_urls)

    # 5C: Art Panel (Recraft digital_illustration)
    print("\n--- 5C: Art Panel (Recraft V3 digital) ---")
    gen_recraft("5C", "art-panel", PROMPT_5C,
                "digital_illustration",
                ["#2D0050", "#C5A017", "#10B5A7"],
                "portrait_4_3")

    # 7A: Contact Sheet (Nano Banana Pro + anchor)
    print("\n--- 7A: Contact Sheet (Nano Banana Pro) ---")
    anchor_urls_7a = []
    if os.path.exists(STYLE_ANCHOR):
        if PROVIDER == "fal":
            anchor_url = fal_client.upload_file(STYLE_ANCHOR)
            anchor_urls_7a = [anchor_url]
    ref_7a = get_ref_image("7A")
    if ref_7a:
        print(f"  Adding composition ref: {os.path.basename(ref_7a)}")
        if PROVIDER == "fal":
            anchor_urls_7a.append(fal_client.upload_file(ref_7a))
    gen_nano_banana("7A", "contact-sheet", PROMPT_7A, "1:1", anchor_urls_7a)

    # 3C: The Plumber Manga Cover (Recraft digital_illustration)
    print("\n--- 3C: The Plumber — Manga Episode Cover (Recraft V3 digital) ---")
    gen_recraft("3C", "plumber-manga-cover", PROMPT_3C,
                "digital_illustration",
                ["#070B1D", "#C5A017", "#F0EDE3"],
                "portrait_4_3")

    # 3D: 16 Engine Icon System (5 batches, Recraft vector_illustration)
    print("\n--- 3D: 16 Engine Icon System (5 batches) ---")

    print("\n--- 3D-1: Vedic Engine Icons (4 icons) ---")
    gen_recraft("3D1", "vedic-engine-icons", PROMPT_3D1,
                "vector_illustration",
                ["#070B1D", "#F0EDE3"],
                "square_hd")

    print("\n--- 3D-2: Western Engine Icons (4 icons) ---")
    gen_recraft("3D2", "western-engine-icons", PROMPT_3D2,
                "vector_illustration",
                ["#070B1D", "#F0EDE3"],
                "square_hd")

    print("\n--- 3D-3: Bridge Engine Icons (3 icons) ---")
    gen_recraft("3D3", "bridge-engine-icons", PROMPT_3D3,
                "vector_illustration",
                ["#070B1D", "#F0EDE3"],
                "square_hd")

    print("\n--- 3D-4: Somatic & Resonance Icons (3 icons) ---")
    gen_recraft("3D4", "somatic-engine-icons", PROMPT_3D4,
                "vector_illustration",
                ["#070B1D", "#F0EDE3"],
                "square_hd")

    print("\n--- 3D-5: Forge & Geometry Icons (2 icons) ---")
    gen_recraft("3D5", "forge-engine-icons", PROMPT_3D5,
                "vector_illustration",
                ["#070B1D", "#F0EDE3"],
                "square_hd")

    print("\n" + "=" * 60)
    print("  ILLUSTRATIONS COMPLETE (5A-5D + 7A + 3C + 3D)")
    print("=" * 60)


if __name__ == "__main__":
    main()
