# Cloudflare Pages configuration
# https://developers.cloudflare.com/pages/

# Build configuration
build:
  command: bun run build
  output_directory: out

# Environment variables
env_vars:
  NODE_ENV: production
  NEXT_PUBLIC_APP_URL: https://somatic-canticles.pages.dev
  NEXT_PUBLIC_API_URL: https://api.somatic-canticles.com
  NEXT_PUBLIC_ENABLE_ANALYTICS: true
  NEXT_PUBLIC_ENABLE_SENTRY: true

# Preview environment
preview:
  env_vars:
    NODE_ENV: development
    NEXT_PUBLIC_APP_URL: https://preview.somatic-canticles.pages.dev
    NEXT_PUBLIC_API_URL: https://api-dev.somatic-canticles.com
    NEXT_PUBLIC_ENABLE_ANALYTICS: false
    NEXT_PUBLIC_ENABLE_SENTRY: true
